version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
