version: '3.8'

services:
  api-ci:
    container_name: kovyra-api-ci
    build:
      context: ../../..
      dockerfile: server/docker/ci/Dockerfile
    environment:
      - NODE_ENV=ci
      - CI=true
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db-ci:5432/${POSTGRES_DB:-kovyra_test}
    depends_on:
      db-ci:
        condition: service_healthy
    networks:
      - kovyra-ci-network

  db-ci:
    container_name: kovyra-db-ci
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-kovyra_test}
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - kovyra-ci-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-kovyra_test}']
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  kovyra-ci-network:
    name: kovyra-network-ci
    driver: bridge
